### ISSUE TITLE
[PUT] users/{id}/password: Returns HTTP 500 instead of 400

### ISSUE THREAD

**Issue by MoritzHahn1337** [ghga-de/datameta#167]
The put request for users/{id}/password should return HTTP 400 if the new password is too short. Instead, HTTP 500 ist returned.

```
2021-03-11 10:24:39,574 ERROR [waitress:404][waitress-0] Exception while serving /api/v0/users/27f9715e-c922-40fa-a8fe-96a1c5bb8d65/password
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/usr/local/lib/python3.8/site-packages/pyramid/view.py", line 786, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/waitress/channel.py", line 397, in service
    task.service()
  File "/usr/local/lib/python3.8/site-packages/waitress/task.py", line 168, in service
    self.execute()
  File "/usr/local/lib/python3.8/site-packages/waitress/task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/usr/local/lib/python3.8/site-packages/pyramid_retry/__init__.py", line 127, in retry_policy
    response = router.invoke_request(request)
  File "/usr/local/lib/python3.8/site-packages/pyramid/router.py", line 245, in invoke_request
    response = handle_request(request)
  File "/usr/local/lib/python3.8/site-packages/pyramid_openapi3/tween.py", line 28, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.8/site-packages/pyramid_tm/__init__.py", line 178, in tm_tween
    reraise(*exc_info)
  File "/usr/local/lib/python3.8/site-packages/pyramid_tm/compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/pyramid_tm/__init__.py", line 143, in tm_tween
    response = handler(request)
  File "/usr/local/lib/python3.8/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/usr/local/lib/python3.8/site-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/usr/local/lib/python3.8/site-packages/pyramid/util.py", line 733, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.8/site-packages/pyramid/router.py", line 143, in handle_request
    response = _call_view(
  File "/usr/local/lib/python3.8/site-packages/pyramid/view.py", line 674, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.8/site-packages/pyramid/config/views.py", line 170, in attr_view
    return view(context, request)
  File "/usr/local/lib/python3.8/site-packages/pyramid/config/views.py", line 196, in predicate_wrapper
    return view(context, request)
  File "/usr/local/lib/python3.8/site-packages/pyramid_openapi3/__init__.py", line 116, in wrapper_view
    return view(context, request)
  File "/usr/local/lib/python3.8/site-packages/pyramid/viewderivers.py", line 427, in rendered_view
    result = view(context, request)
  File "/usr/local/lib/python3.8/site-packages/pyramid/viewderivers.py", line 141, in _requestonly_view
    response = view(request)
  File "/workspace/datameta/api/password.py", line 80, in put
    raise errors.get_validation_error([error])
TypeError: get_validation_error() missing 1 required positional argument: 'fields'
```

**Comment by lkuchenb** [comment]
I think the issue with `fields` being required was fixed by @KerstenBreuer at some time, but it may be that the corresponding branch is not yet merged 🤔

**Comment by lkuchenb** [comment]
@KerstenBreuer @MoritzHahn1337 apparently I was mistaken, I added a PR
